name: Build and Test

on:
  push:
    branches: [branchMake]
  pull_request:
    branches: [branchMake]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up C++ Build Environment
        run: sudo apt update && sudo apt install -y g++
      - name: Build with Makefile
        run: |
          make clean
          make
      - name: Run Tests
        run: ./funcA
      - name: Build tarball
        run: |
          make dist
          ls myprogram-1.0.tar.gz
          tar -tzf myprogram-1.0.tar.gz
