name: CI

on:
    push:
      branches: ["branchAutomake"]
    pull_request:
      branches: ["branchAutomake"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up C++ Build Environment
        run: sudo apt update && sudo apt install -y g++
      - name: Build with Makefile
        run: |
          make clean
          make
          ./main
      - name: Build tarball
        run: |
          make dist
          ls myprogram-1.0.tar.gz
